"""
Track 2 — Prompt Golf.

Students submit a single prompt template plus the (input, output) samples
they generated by running it. The platform asks the LLM-as-judge how
correct each output is against a hidden gold answer, then divides by the
estimated total token cost. Lower-token, higher-accuracy prompts win.

Headline metric (per PLAN.md):
  judge_accuracy / total_tokens   (higher is better)

Because `final_score` lives in [0, 1], we report the raw efficiency in
`judge_metadata` and translate to the platform's range with a baseline
budget (the gold file states a `baseline_tokens_per_sample` that pins
final_score = judge_accuracy when a student spends exactly the baseline):

  efficiency  = min(1.0, baseline_tokens_total / max(1, total_tokens))
  final_score = judge_accuracy * efficiency

Why clamp efficiency at 1.0: without the clamp, students would race toward
absurdly short prompts ("Answer:") that happen to score well on a couple
of trivia questions. Clamping removes that incentive — accuracy is the
ceiling, efficiency only takes you back down toward it.

Token counting is approximate (chars/4 — the standard English rule of
thumb). We do not have access to the real tokenizer the student used
client-side, and bringing in `tiktoken` for an approximation we will
re-derive on the server is not worth the dependency. This is documented
in the public rubric so students know how scoring works.

The judge is injected (not constructed inside the function) so that the
test suite can pass `FakeJudge` and CI never hits the real Anthropic API.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from api.schemas import (
    PromptGolfPayload,
    ScoreDimension,
    ScoreResult,
    Submission,
    TRACK_PROMPT_GOLF,
)
from evaluator.judge import JudgeBackend


# Default if the gold file does not pin a baseline. ~150 input + 50 output is
# a reasonable budget for one short prompt + one short answer.
_DEFAULT_BASELINE_TOKENS_PER_SAMPLE = 200

# Loaded lazily: the judge prompt is the same correctness rubric Track 3 uses.
_PROMPT_PATH = Path(__file__).resolve().parent.parent.parent / "prompts" / "judge_correctness.txt"


def _estimate_tokens(text: str) -> int:
    """Rough token estimate using the ~4-chars-per-token rule of thumb.

    Returns 0 for the empty string and at least 1 for any non-empty input
    (so a one-character prompt isn't accidentally "free").
    """
    if not text:
        return 0
    return max(1, len(text) // 4)


def _load_judge_prompt() -> str:
    return _PROMPT_PATH.read_text(encoding="utf-8")


def _build_user_message(prompt_template: str, input_text: str, student_output: str, expected_output: str) -> str:
    """Render the (input, expected, actual) tuple into the user message the
    judge sees. The judge prompt itself is the system message."""
    return (
        f"PROMPT TEMPLATE THE STUDENT USED:\n{prompt_template}\n\n"
        f"INPUT:\n{input_text}\n\n"
        f"GOLD REFERENCE ANSWER:\n{expected_output}\n\n"
        f"STUDENT'S ANSWER:\n{student_output}\n"
    )


def score_prompt_golf(
    submission: Submission,
    gold: Mapping[str, Any],
    *,
    judge: JudgeBackend | None,
) -> ScoreResult:
    """Score a Prompt Golf submission.

    Args:
        submission: Validated student submission. track_id must be 'prompt_golf'.
        gold: Mapping with keys:
            - 'items': list of {'input': str, 'expected_output': str}
            - 'baseline_tokens_per_sample': optional int (default 200)
        judge: A JudgeBackend (real AnthropicJudge in prod, FakeJudge in tests).
            Required — Track 2 cannot score without one.

    Returns:
        ScoreResult with final_score = judge_accuracy * efficiency, both
        clamped to [0, 1]. Raw `judge_accuracy / total_tokens` (the headline
        metric named in PLAN.md) is recorded in judge_metadata for transparency.
    """
    if submission.track_id != TRACK_PROMPT_GOLF:
        raise ValueError(
            f"score_prompt_golf called with track_id={submission.track_id!r}; "
            f"expected {TRACK_PROMPT_GOLF!r}"
        )
    if judge is None:
        raise ValueError("score_prompt_golf requires a judge; got None")

    payload = submission.track_payload
    assert isinstance(payload, PromptGolfPayload)

    gold_items = list(gold.get("items") or [])
    if not gold_items:
        raise ValueError("gold for prompt_golf must contain at least one item")
    expected_by_input = {it["input"]: it["expected_output"] for it in gold_items}
    baseline_per_sample = int(
        gold.get("baseline_tokens_per_sample", _DEFAULT_BASELINE_TOKENS_PER_SAMPLE)
    )

    sample_inputs = [s.input for s in payload.samples]
    duplicates = [k for k, n in Counter(sample_inputs).items() if n > 1]
    if duplicates:
        raise ValueError(f"duplicate sample input(s): {sorted(duplicates)}")

    sample_input_set = set(sample_inputs)
    gold_input_set = set(expected_by_input)
    unknown = sample_input_set - gold_input_set
    missing = gold_input_set - sample_input_set
    if unknown:
        raise ValueError(f"unknown sample input(s) (not in gold): {sorted(unknown)}")
    if missing:
        raise ValueError(f"missing samples for gold input(s): {sorted(missing)}")

    system_prompt = _load_judge_prompt()

    per_sample: list[dict[str, Any]] = []
    judge_scores: list[float] = []
    judge_tokens_in_total = 0
    judge_tokens_out_total = 0

    # Prompt-template tokens are charged once per sample because that's how the
    # student's run actually billed (no caching client-side, and we want the
    # signal "shorter template → lower cost" to come through clearly).
    prompt_template_tokens = _estimate_tokens(payload.prompt_template)
    student_total_tokens = 0

    for sample in payload.samples:
        expected = expected_by_input[sample.input]
        user_msg = _build_user_message(
            payload.prompt_template, sample.input, sample.output, expected
        )
        response = judge.call(system=system_prompt, user=user_msg)
        judge_scores.append(response.score)
        judge_tokens_in_total += response.tokens_in
        judge_tokens_out_total += response.tokens_out

        in_tokens = prompt_template_tokens + _estimate_tokens(sample.input)
        out_tokens = _estimate_tokens(sample.output)
        per_sample_tokens = in_tokens + out_tokens
        student_total_tokens += per_sample_tokens

        per_sample.append({
            "input": sample.input,
            "score": round(response.score, 6),
            "estimated_input_tokens": in_tokens,
            "estimated_output_tokens": out_tokens,
            "judge_reasoning": response.reasoning,
        })

    judge_accuracy = sum(judge_scores) / len(judge_scores)
    baseline_total = baseline_per_sample * len(payload.samples)
    efficiency = min(1.0, baseline_total / max(1, student_total_tokens))
    final_score = max(0.0, min(1.0, judge_accuracy * efficiency))

    # Headline metric named in PLAN.md, kept for transparency. Guard the
    # divisor: a degenerate empty submission would still parse but should
    # not divide by zero.
    raw_efficiency_per_token = (
        judge_accuracy / student_total_tokens if student_total_tokens > 0 else 0.0
    )

    return ScoreResult(
        submission_id=submission.submission_id,
        student_id=submission.student_id,
        track_id=TRACK_PROMPT_GOLF,
        final_score=round(final_score, 6),
        dimensions=[
            ScoreDimension(
                name="judge_accuracy_per_token",
                weight=1.0,
                raw_score=round(final_score, 6),
                notes=(
                    f"accuracy={judge_accuracy:.3f}, "
                    f"tokens={student_total_tokens} (baseline {baseline_total}), "
                    f"efficiency={efficiency:.3f}"
                ),
            )
        ],
        judge_metadata={
            "n_samples": len(payload.samples),
            "judge_accuracy": round(judge_accuracy, 6),
            "estimated_total_tokens": student_total_tokens,
            "baseline_total_tokens": baseline_total,
            "efficiency": round(efficiency, 6),
            "raw_accuracy_per_token": round(raw_efficiency_per_token, 9),
            "judge_tokens_in": judge_tokens_in_total,
            "judge_tokens_out": judge_tokens_out_total,
            "per_sample": per_sample,
        },
    )
